build:
    tags:
      - docker
    stage: build
    only:
      - tags
    image: docker:19.03.8
    services:
      - name: docker:19.03.8-dind
    before_script:
      - docker --version
      - mkdir -p ~/.docker/cli-plugins
      - wget https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64 -O docker-buildx
      - mv docker-buildx ~/.docker/cli-plugins/docker-buildx
      - chmod a+x ~/.docker/cli-plugins/docker-buildx
      - docker buildx version
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - echo $IMAGE_NAME:$CI_COMMIT_TAG
    script:
      - docker buildx create --use
      - docker buildx ls
      - docker buildx build --push -t $IMAGE_NAME:latest -t $IMAGE_NAME:$CI_COMMIT_TAG --platform linux/amd64,linux/arm/v7,linux/arm64 .
