version: '3'

volumes:
  mariadb_data:


services:
  db:
    image: mariadb:11.8.1-ubi-rc
    container_name: sms-gateway_db
    restart: always
    command: --wait_timeout=28800 --interactive_timeout=28800
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=UP5yeFxRcvtMBzjdfNmT6p
      - MYSQL_USER=sms-gateway
      - MYSQL_PASSWORD=Bpj7hXNCextgnzSWckFybV
      - MYSQL_DATABASE=smsd
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 15s
      interval: 15s
      timeout: 5s
      retries: 5
  gammu_modem_9210923872:
    #image: fizcko/sms-gateway:latest
    build: .
    container_name: sim_9210923872
    restart: "no"
    ports:
      - 5000:5000
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=62.76.233.147
      - MYSQL_USER=smsd
      - MYSQL_PASSWORD=@A11bb22cc
      - MYSQL_DATABASE=smsd
      - GAMMU_DEVICE=/dev/ttyUSB0
      - PHONE_ID=3872
  gammu_modem_9214359834:
    #image: fizcko/sms-gateway:latest
    build: .
    container_name:  sim_9214359834
    restart: "no"
    ports:
      - 5001:5000
    devices:
      - "/dev/ttyUSB5:/dev/ttyUSB5"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=62.76.233.147
      - MYSQL_USER=smsd
      - MYSQL_PASSWORD=@A11bb22cc
      - MYSQL_DATABASE=smsd
      - GAMMU_DEVICE=/dev/ttyUSB5
      - PHONE_ID=9834

