version: '3'

volumes:
  mariadb_data:

services:
  db:
    image: mariadb:11.4-ubi
    container_name: sms-gateway_db
    restart: always
    command: --wait_timeout=28800 --interactive_timeout=28800
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=UP5yeFxRcvtMBzjdfNmT6p
      - MYSQL_USER=sms-gateway
      - MYSQL_PASSWORD=Bpj7hXNCextgnzSWckFybV
      - MYSQL_DATABASE=smsd
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 15s
      interval: 15s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    container_name: sms-gateway_adminer # Рекомендуется давать контейнеру имя
    restart: always
    ports:
      - 8080:8080
  gammu_modem_357224028610991:
    #image: fizcko/sms-gateway:latest
    build: .
    container_name:  sim_9210923954
    restart: always
    privileged: true
    ports:
      - 5001:5000
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=sms-gateway
      - MYSQL_PASSWORD=Bpj7hXNCextgnzSWckFybV
      - MYSQL_DATABASE=smsd
      - GAMMU_DEVICE=/dev/ttyUSB0
      - PHONE_ID=3954




