version: '3'

volumes:
  mariadb_data:

services:
  db:
    image: mariadb:11.4-ubi
    container_name: sms-gateway_db
    restart: always
    command: --wait_timeout=28800 --interactive_timeout=28800
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=UP5yeFxRcvtMBzjdfNmT6p
      - MYSQL_USER=sms-gateway
      - MYSQL_PASSWORD=Bpj7hXNCextgnzSWckFybV
      - MYSQL_DATABASE=smsd
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 15s
      interval: 15s
      timeout: 5s
      retries: 5
  gammu_modem_9210923872:
    image: fizcko/sms-gateway:latest
    #build: .
    container_name: sim_9210923872
    restart: always
    ports:
      - 5000:5000
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=sms-gateway
      - MYSQL_PASSWORD=Bpj7hXNCextgnzSWckFybV
      - MYSQL_DATABASE=smsd
      - GAMMU_DEVICE=/dev/ttyUSB0
  gammu_modem:
    image: fizcko/sms-gateway:latest
    #build: .
    container_name: sms-gateway_server
    restart: always
    ports:
      - 5000:5001
    devices:
      - "/dev/serial/by-id/usb-HUAWEI_Technology_HUAWEI_Mobile-if00-port0:/dev/usb-HUAWEI_Technology_HUAWEI_Mobile-if00-port0"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=sms-gateway
      - MYSQL_PASSWORD=Bpj7hXNCextgnzSWckFybV
      - MYSQL_DATABASE=smsd
      - GAMMU_DEVICE=/dev/usb-HUAWEI_Technology_HUAWEI_Mobile-if00-port0"

